export function renderFishSnippet(): string {
  return `# Auto-generated by cmux-open-file. Do not edit directly.

bind @ '__cmux_open_file_at_trigger'

function __cmux_open_file_at_trigger
    if test -z (commandline)
        set -l selected (cmux-open-file pick </dev/tty 2>/dev/tty)
        if test $status -eq 0 -a -n "$selected"
            commandline -i "@ $selected"
        end
        commandline -f repaint
    else
        commandline -i '@'
    end
end

function @
    cmux-open-file open $argv
end
`;
}
