export function renderFishSnippet(): string {
  return `# Auto-generated by cmux-open-file. Do not edit directly.

# '@' を押したらインラインの fuzzy ピッカーを起動する。
# - コマンドラインが空: 空クエリで起動
# - 既に '@ xxx' を編集中: xxx を初期クエリにして再起動
# - その他 (入力途中): 普通に '@' を挿入
bind @ '__cmux_open_file_at_trigger'

function __cmux_open_file_at_trigger
    set -l line (commandline)
    set -l initial_query ''

    if test -z "$line"
        # ok, launch picker with empty query
    else if string match -q '@ *' -- "$line"
        set initial_query (string sub --start 3 -- "$line")
        commandline ''  # 旧 '@ xxx' を消して、ピッカーが '@ ' を含めて描画する
    else
        commandline -i '@'
        return
    end

    set -l selected (cmux-open-file pick "$initial_query" </dev/tty 2>/dev/tty)
    if test $status -eq 0 -a -n "$selected"
        commandline -i "@ $selected"
    else
        # キャンセル: 元の commandline を復元 (空ならそのまま空)
        commandline "$line"
    end
    commandline -f repaint
end

# '@' コマンド本体: 引数 (ファイルパス) を受け取って cmux に展開
function @
    cmux-open-file open $argv
end
`;
}
