import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";

export async function installFishIntegration(): Promise<string> {
  const home = process.env.HOME || homedir();
  const dir = join(home, ".config/fish/conf.d");
  await mkdir(dir, { recursive: true });
  const path = join(dir, "cmux-open-file.fish");
  const content = `# Auto-generated by cmux-open-file install. Do not edit.
cmux-open-file init fish | source
`;
  await writeFile(path, content, "utf-8");
  return path;
}
